import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Banknote, Check, ChevronRight, Globe2, MapPin, ShieldCheck, WifiOff } from 'lucide-react';
import AppDownloadSection from './AppDownloadSection';
import CountryQuickSelect from './CountryQuickSelect';
import LanguageMenu from './LanguageMenu';
import Logo from './Logo';
import SiteFooter from './SiteFooter';
import { OfflinePhoneIllustration, RateCheckIllustration, TravelRouteIllustration } from './HomeIllustrations';

function ConverterPreview({ fr }) {
  return <div className="overflow-hidden rounded-[30px] border border-slate-200/80 bg-white shadow-[0_28px_90px_rgba(15,23,42,.1)] dark:border-white/10 dark:bg-slate-900">
    <div className="grid md:grid-cols-2"><div className="border-b border-slate-200 p-5 md:border-b-0 md:border-r dark:border-white/10"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">{fr?'Vous envoyez':'You send'}</p><p className="mt-5 text-4xl font-semibold tracking-[-.05em]">100</p><div className="mt-6 flex items-center justify-between rounded-2xl border border-slate-200 px-4 py-3 dark:border-white/10"><div><p className="text-sm font-semibold">EUR</p><p className="text-xs text-slate-400">Euro</p></div><span className="text-xl">🇪🇺</span></div></div><div className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">{fr?'Vous recevez':'You receive'}</p><p className="mt-5 text-4xl font-semibold tracking-[-.05em]">7 820</p><div className="mt-6 flex items-center justify-between rounded-2xl border border-slate-200 px-4 py-3 dark:border-white/10"><div><p className="text-sm font-semibold">GMD</p><p className="text-xs text-slate-400">Dalasi</p></div><span className="text-xl">🇬🇲</span></div></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-slate-50/80 px-5 py-3.5 text-xs dark:border-white/10 dark:bg-white/[.025]"><span className="font-semibold">1 EUR = 78,20 GMD</span><span className="inline-flex items-center gap-1.5 text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>{fr?'Taux synchronisé':'Rate synced'}</span></div>
  </div>;
}

function DestinationLink({ flag, country, currency, code }) {
  return <Link href={`/app?tab=travel&country=${code}`} className="group flex items-center justify-between rounded-2xl border border-slate-200/80 bg-white px-4 py-3 transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-[0_12px_30px_rgba(15,23,42,.06)] dark:border-white/10 dark:bg-white/[.03]"><span className="flex min-w-0 items-center gap-3"><span className="text-xl">{flag}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{country}</span><span className="text-xs text-slate-400">{currency}</span></span></span><ChevronRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-emerald-600"/></Link>;
}

export default function KiwangoHome() {
  const [lang, setLang] = useState('fr');
  const fr = lang === 'fr';
  useEffect(() => { const saved = localStorage.getItem('app_lang'); if (saved === 'fr' || saved === 'en') setLang(saved); }, []);
  const changeLang = (value) => { setLang(value); localStorage.setItem('app_lang', value); };
  const selectCountry = (country) => { localStorage.setItem('kiwango_quick_destination', country.code); window.location.href = `/app?tab=travel&country=${country.code}`; };

  return <div className="min-h-screen overflow-x-clip bg-white text-slate-950 dark:bg-slate-950 dark:text-white">
    <div className="sticky top-0 z-[140] px-3 pt-3 sm:px-5 sm:pt-4"><header className="mx-auto flex h-[64px] w-full max-w-6xl items-center justify-between rounded-[22px] border border-slate-200/70 bg-white/90 px-3 shadow-[0_12px_40px_rgba(15,23,42,.07)] backdrop-blur-xl dark:border-white/10 dark:bg-slate-900/90 sm:px-4"><Logo size="md" showText/><nav className="hidden items-center gap-1 lg:flex">{[[fr?'Convertir':'Convert','/app?tab=converter'],[fr?'Voyage':'Travel','/app?tab=travel'],[fr?'Outils':'Tools','/app?tab=tools'],[fr?'Devises':'Currencies','/app?tab=rates']].map(([label,href])=><Link key={href} href={href} className="rounded-full px-4 py-2 text-sm font-medium text-slate-500 transition hover:bg-slate-100 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-white/5 dark:hover:text-white">{label}</Link>)}</nav><div className="flex items-center gap-2"><CountryQuickSelect lang={lang} onSelect={selectCountry}/><LanguageMenu value={lang} onChange={changeLang}/><Link href="/app" className="hidden rounded-full bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-emerald-700 dark:bg-white dark:text-slate-950 sm:inline-flex">{fr?'Ouvrir Kiwango':'Open Kiwango'}</Link></div></header></div>

    <main>
      <section className="mx-auto w-full max-w-6xl px-4 pb-16 pt-14 md:px-6 lg:pb-24 lg:pt-20"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="max-w-xl"><div className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500"/>{fr?'Compagnon financier de voyage':'Travel money companion'}</div><h1 className="mt-5 text-[44px] font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl">{fr?'Votre argent, plus simple à comprendre quand vous voyagez.':'Your money, easier to understand when you travel.'}</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-500 sm:text-lg">{fr?'Convertissez, vérifiez un taux, préparez la monnaie de votre destination et gardez vos repères même sans connexion.':'Convert, check a rate, prepare your destination currency and keep your bearings even without a connection.'}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/app?tab=converter" className="inline-flex items-center gap-2 rounded-full bg-emerald-600 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-emerald-700">{fr?'Commencer à convertir':'Start converting'}<ArrowRight className="h-4 w-4"/></Link><a href="#download" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-slate-300 dark:border-white/10 dark:bg-white/5 dark:text-slate-200">{fr?'Installer l’application':'Get the app'}</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-400"><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-emerald-600"/>{fr?'Sans compte':'No account'}</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-emerald-600"/>Offline-first</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-emerald-600"/>{fr?'Données locales':'Local data'}</span></div></div><div className="relative"><div className="absolute -left-8 -top-10 h-32 w-32 rounded-full bg-emerald-100 blur-3xl"/><ConverterPreview fr={fr}/><div className="absolute -bottom-5 -left-4 hidden rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-[0_18px_45px_rgba(15,23,42,.12)] md:block dark:border-white/10 dark:bg-slate-900"><p className="text-[10px] uppercase tracking-[.14em] text-slate-400">Rate Check</p><p className="mt-1 text-sm font-semibold text-emerald-700">{fr?'Taux proposé : acceptable':'Offered rate: fair'}</p></div></div></div></section>

      <section className="border-y border-slate-200/70 bg-[#fbfcfb] py-16 dark:border-white/10 dark:bg-white/[.015]"><div className="mx-auto grid w-full max-w-6xl gap-10 px-4 md:px-6 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><TravelRouteIllustration/><div className="max-w-xl lg:pl-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-700">Travel Pack</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{fr?'Choisissez le pays. Kiwango prépare sa monnaie.':'Choose the country. Kiwango prepares its currency.'}</h2><p className="mt-5 text-sm leading-7 text-slate-500 sm:text-base">{fr?'Chaque destination garde sa propre fiche, même lorsque plusieurs pays utilisent la même devise. Synchronisez les taux utiles avant de partir et retrouvez-les hors connexion.':'Every destination keeps its own profile, even when several countries share a currency. Sync useful rates before departure and keep them offline.'}</p><div className="mt-7 grid gap-2 sm:grid-cols-2"><DestinationLink flag="🇬🇲" country={fr?'Gambie':'Gambia'} currency="GMD · Dalasi" code="GM"/><DestinationLink flag="🇨🇮" country={fr?"Côte d’Ivoire":"Ivory Coast"} currency="XOF · Franc CFA" code="CI"/><DestinationLink flag="🇬🇭" country="Ghana" currency="GHS · Cedi" code="GH"/><DestinationLink flag="🇰🇪" country="Kenya" currency="KES · Shilling" code="KE"/></div><Link href="/app?tab=travel" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700">{fr?'Voir toutes les destinations':'See all destinations'}<ArrowRight className="h-4 w-4"/></Link></div></div></section>

      <section className="mx-auto w-full max-w-6xl px-4 py-20 md:px-6"><div className="mb-10 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">{fr?'Décidez avec le bon contexte':'Decide with the right context'}</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{fr?'Savoir combien vaut une devise ne suffit pas toujours.':'Knowing a rate is not always enough.'}</h2></div><div className="grid gap-6 lg:grid-cols-2"><RateCheckIllustration/><div className="flex flex-col justify-center rounded-[30px] border border-slate-200/80 p-7 sm:p-9 dark:border-white/10"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30"><Banknote className="h-5 w-5"/></div><h3 className="mt-6 text-2xl font-semibold tracking-[-.03em]">Rate Check</h3><p className="mt-3 text-sm leading-7 text-slate-500 sm:text-base">{fr?'Comparez le taux réellement proposé au taux de référence, voyez ce que vous devriez recevoir et mesurez immédiatement l’écart.':'Compare the rate you are actually offered with the reference rate, see what you should receive and measure the difference instantly.'}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.03]"><p className="text-xs text-slate-400">{fr?'Montant attendu':'Expected'}</p><p className="mt-1 text-lg font-semibold">7 820 GMD</p></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.03]"><p className="text-xs text-slate-400">{fr?'Écart estimé':'Estimated gap'}</p><p className="mt-1 text-lg font-semibold text-emerald-700">−1,5 %</p></div></div><Link href="/app?tab=tools" className="mt-7 inline-flex items-center gap-2 self-start rounded-full bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-slate-950">{fr?'Explorer les outils':'Explore tools'}<ArrowRight className="h-4 w-4"/></Link></div></div></section>

      <section className="mx-auto grid w-full max-w-6xl gap-6 px-4 pb-20 md:px-6 lg:grid-cols-2"><div className="rounded-[32px] border border-slate-200/80 bg-[#fbfcfb] p-7 sm:p-9 dark:border-white/10 dark:bg-white/[.02]"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-700"><WifiOff className="h-4 w-4"/>{fr?'Pensé pour les moments sans réseau':'Built for moments without a network'}</div><h2 className="mt-4 max-w-md text-3xl font-semibold tracking-[-.04em]">{fr?'Préparez maintenant. Utilisez plus tard, même hors connexion.':'Prepare now. Use later, even offline.'}</h2><p className="mt-4 max-w-lg text-sm leading-7 text-slate-500">{fr?'Les taux synchronisés et Travel Packs restent sur votre appareil. Vous savez toujours quand une donnée a été mise à jour.':'Synced rates and Travel Packs stay on your device. You always know when data was last updated.'}</p><div className="mt-7 inline-flex rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500 dark:border-white/10 dark:bg-white/5">PWA · IndexedDB · Offline-first</div></div><OfflinePhoneIllustration/></section>

      <AppDownloadSection lang={lang}/>

      <section className="mx-auto w-full max-w-6xl px-4 pb-20 md:px-6"><div className="grid overflow-hidden rounded-[34px] bg-slate-950 text-white lg:grid-cols-[1.15fr_.85fr]"><div className="p-7 sm:p-10 lg:p-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-300">Kiwango</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{fr?'Une seule app pour convertir, préparer, vérifier et suivre votre argent en voyage.':'One app to convert, prepare, check and track your travel money.'}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-400">{fr?'Le convertisseur, le voyage, le budget, le Cash Wallet, les frais et les services à proximité vivent dans la même expérience.':'Conversion, travel, budget, Cash Wallet, fees and nearby services live in one experience.'}</p><Link href="/app" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950">{fr?'Ouvrir l’application':'Open the app'}<ArrowRight className="h-4 w-4"/></Link></div><div className="relative min-h-[300px] overflow-hidden border-t border-white/10 bg-emerald-500/10 p-8 lg:border-l lg:border-t-0"><Globe2 className="absolute -bottom-12 -right-10 h-72 w-72 text-emerald-400/10"/><div className="relative space-y-3"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><p className="text-xs text-slate-400">{fr?'Budget restant':'Budget remaining'}</p><p className="mt-1 text-2xl font-semibold">184 500 XOF</p></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><p className="text-xs text-slate-400">Cash Wallet</p><p className="mt-1 text-2xl font-semibold">2 850 GMD</p></div><div className="flex items-center gap-2 rounded-2xl bg-emerald-400/10 p-4 text-sm text-emerald-200"><MapPin className="h-4 w-4"/>{fr?'3 services financiers à proximité':'3 nearby financial services'}</div></div></div></div></section>
    </main>
    <SiteFooter lang={lang}/>
  </div>;
}
