import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Compass, CreditCard, Lightbulb, Loader2, MapPin, Navigation, RefreshCw } from 'lucide-react';
import { calculateCrossRate } from '../lib/rates';

const number = (v) => Number(String(v ?? '').replace(/\s/g, '').replace(',', '.'));
const fmt = (n, locale = 'fr-FR', digits = 2) => Number.isFinite(n) ? new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(n) : '—';
const read = (key, fallback) => { if (typeof window === 'undefined') return fallback; try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };

export default function KiwangoInsights({ allRates = {}, currencies = [], lang = 'fr' }) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const [section, setSection] = useState('trends');
  const buttons = [['trends','Tendance',BarChart3],['payments','Comparer',CreditCard],['nearby','Autour de moi',Compass],['coach','Mon résumé',Lightbulb]];
  return <section className="mt-8 min-w-0 rounded-[30px] border border-slate-200/80 bg-slate-50/70 p-4 sm:p-6 dark:border-white/10 dark:bg-white/[.025]"><div className="mb-5 flex flex-wrap items-center gap-2">{buttons.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`inline-flex items-center gap-2 rounded-full px-3.5 py-2 text-xs font-semibold transition ${section===id?'bg-emerald-600 text-white':'bg-white text-slate-600 hover:bg-slate-100 dark:bg-white/5 dark:text-slate-300'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div>{section==='trends'&&<Trends currencies={currencies} locale={locale}/>} {section==='payments'&&<PaymentCompare allRates={allRates} currencies={currencies} locale={locale}/>} {section==='nearby'&&<Nearby/>} {section==='coach'&&<Coach allRates={allRates} locale={locale}/>}</section>;
}

function CurrencySelect({ value, onChange, currencies }) { return <select value={value} onChange={onChange} className="min-w-0 max-w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-slate-950">{currencies.map(c=><option key={c.code} value={c.code}>{c.code} · {c.name}</option>)}</select>; }

function Trends({ currencies, locale }) {
  const [base,setBase]=useState('EUR'); const [quote,setQuote]=useState('GMD'); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/historical-rates?base=${base}&quote=${quote}&days=30`);const json=await r.json();if(!r.ok)throw new Error(json.error||'Unavailable');setData(json)}catch(e){setData(null);setError(e.message)}finally{setLoading(false)}},[base,quote]);
  useEffect(()=>{load()},[load]);
  const stats=useMemo(()=>{const values=data?.series?.map(p=>p.rate)||[];if(!values.length)return null;const current=values[values.length-1],avg=values.reduce((a,b)=>a+b,0)/values.length;return{current,avg,min:Math.min(...values),max:Math.max(...values),delta:(current/avg-1)*100}},[data]);
  const points=useMemo(()=>{if(!stats||!data?.series?.length)return'';const values=data.series.map(p=>p.rate);const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>`${(i/(values.length-1))*100},${92-((v-min)/range)*80}`).join(' ')},[data,stats]);
  return <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><CurrencySelect value={base} onChange={e=>setBase(e.target.value)} currencies={currencies}/><span className="text-slate-400">→</span><CurrencySelect value={quote} onChange={e=>setQuote(e.target.value)} currencies={currencies}/><button onClick={load} className="rounded-full p-2.5 text-slate-500 hover:bg-white" aria-label="Actualiser"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>{loading&&<div className="mt-6 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Chargement de l’historique réel…</div>}{error&&<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Historique indisponible pour cette paire. Aucune donnée n’est simulée.</div>}{stats&&<div className="mt-5 grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_220px]"><div className="min-w-0 rounded-[24px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-slate-950"><svg viewBox="0 0 100 100" className="h-48 w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#059669" strokeWidth="2.2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="flex justify-between gap-3 text-[10px] text-slate-400"><span>{data.series[0]?.date}</span><span>{data.series[data.series.length-1]?.date}</span></div></div><div className="space-y-2"><Stat label="Actuel" value={`1 ${base} = ${fmt(stats.current,locale,4)} ${quote}`}/><Stat label="Moyenne 30 j" value={fmt(stats.avg,locale,4)}/><Stat label="Vs moyenne" value={`${stats.delta>=0?'+':''}${fmt(stats.delta,locale,2)} %`} accent={stats.delta>=0}/></div></div>}</div>;
}

function PaymentCompare({ allRates, currencies, locale }) {
  const [base,setBase]=useState('EUR'),[quote,setQuote]=useState('XOF'),[amount,setAmount]=useState('100');
  const [methods,setMethods]=useState([{name:'Cash / bureau',pct:1,fixed:0},{name:'Carte bancaire',pct:2.5,fixed:0},{name:'Transfert',pct:1.5,fixed:1}]);
  const rate=calculateCrossRate(base,quote,allRates,'EUR'),amt=number(amount);
  const results=methods.map((m,index)=>({...m,index,received:Number.isFinite(amt)&&rate?Math.max(0,amt-amt*m.pct/100-m.fixed)*rate:null})).sort((a,b)=>(b.received||0)-(a.received||0));
  const update=(index,key,value)=>setMethods(methods.map((m,i)=>i===index?{...m,[key]:key==='name'?value:number(value)||0}:m));
  return <div className="min-w-0"><div className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)]"><CurrencySelect value={base} onChange={e=>setBase(e.target.value)} currencies={currencies}/><CurrencySelect value={quote} onChange={e=>setQuote(e.target.value)} currencies={currencies}/><input value={amount} onChange={e=>setAmount(e.target.value)} className="min-w-0 rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-slate-950" placeholder="Montant"/></div><p className="mt-3 text-xs text-slate-500">Les frais sont personnalisables. Kiwango ne prétend pas connaître les tarifs live d’un opérateur sans source officielle.</p><div className="mt-4 space-y-2">{results.map((m,rank)=><div key={m.index} className="grid min-w-0 gap-2 rounded-2xl border border-slate-200 bg-white p-3 dark:border-white/10 dark:bg-slate-950 sm:grid-cols-[minmax(0,1fr)_90px_90px_minmax(120px,1fr)]"><input value={m.name} onChange={e=>update(m.index,'name',e.target.value)} className="min-w-0 bg-transparent text-sm font-semibold outline-none"/><input value={m.pct} onChange={e=>update(m.index,'pct',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs dark:bg-white/5" aria-label="Frais pourcentage"/><input value={m.fixed} onChange={e=>update(m.index,'fixed',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs dark:bg-white/5" aria-label="Frais fixes"/><strong className={`self-center text-left text-sm sm:text-right ${rank===0?'text-emerald-700 dark:text-emerald-400':''}`}>{fmt(m.received,locale)} {quote}</strong></div>)}</div></div>;
}

function Nearby() {
  const [status,setStatus]=useState('idle'),[items,setItems]=useState([]),[error,setError]=useState(null);
  const find=()=>{if(!navigator.geolocation){setError('Géolocalisation indisponible');return}setStatus('loading');setError(null);navigator.geolocation.getCurrentPosition(async(pos)=>{try{const r=await fetch(`/api/nearby-finance?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&radius=2200`);const json=await r.json();if(!r.ok)throw new Error(json.error||'Erreur');setItems(json.items||[]);setStatus('ready')}catch(e){setError(e.message);setStatus('error')}},()=>{setError('Position refusée ou indisponible');setStatus('error')},{enableHighAccuracy:false,timeout:10000})};
  const labels={atm:'ATM',bank:'Banque',bureau_de_change:'Bureau de change',money_transfer:'Transfert'};
  return <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Services financiers autour de moi</h2><p className="mt-1 text-sm text-slate-500">ATM, banques, bureaux de change et points de transfert issus d’OpenStreetMap.</p></div><button onClick={find} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-slate-950"><Navigation className="h-4 w-4"/>{status==='loading'?'Recherche…':'Utiliser ma position'}</button></div>{error&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}<div className="mt-5 grid min-w-0 gap-2 md:grid-cols-2">{items.slice(0,16).map(item=><a key={item.id} href={`https://www.openstreetmap.org/?mlat=${item.lat}&mlon=${item.lon}#map=18/${item.lat}/${item.lon}`} target="_blank" rel="noreferrer" className="flex min-w-0 items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 transition hover:border-emerald-300 dark:border-white/10 dark:bg-slate-950"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><MapPin className="h-4 w-4"/></span><span className="min-w-0"><strong className="block truncate text-sm">{item.name||labels[item.type]||'Service financier'}</strong><span className="mt-1 block break-words text-xs text-slate-500">{labels[item.type]||item.type}{item.address?` · ${item.address}`:''}</span></span></a>)}</div>{status==='ready'&&!items.length&&<p className="mt-5 text-sm text-slate-500">Aucun service référencé dans ce rayon.</p>}</div>;
}

function Coach({ allRates, locale }) {
  const budget=read('kiwango_budget',null),wallet=read('kiwango_wallet',null),fields=read('kiwango_field_rates',[]),alerts=read('kiwango_alerts',[]);
  const spent=budget?.expenses?.reduce((sum,e)=>sum+Number(e.amount||0),0)||0; const remaining=budget?Number(budget.total||0)-spent:null;
  const eurXof=calculateCrossRate('EUR','XOF',allRates,'EUR');
  return <div><h2 className="text-xl font-semibold">Mon résumé Kiwango</h2><p className="mt-1 text-sm text-slate-500">Une synthèse contextuelle construite localement à partir de vos données. Aucun chatbot générique.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Stat label="Budget restant" value={budget?`${fmt(remaining,locale)} ${budget.currency}`:'Créez un budget'}/><Stat label="Cash disponible" value={wallet?`${fmt(wallet.balance,locale)} ${wallet.currency}`:'Configurez le Cash Wallet'}/><Stat label="Taux EUR/XOF" value={Number.isFinite(eurXof)?fmt(eurXof,locale,3):'Indisponible'}/><Stat label="Alertes / terrain" value={`${alerts.length} alertes · ${fields.length} observations`}/></div><div className="mt-5 rounded-2xl bg-emerald-50 p-5 text-sm leading-6 text-emerald-950 dark:bg-emerald-950/20 dark:text-emerald-100"><Lightbulb className="mb-2 h-5 w-5 text-emerald-600"/>{budget&&remaining<Number(budget.total)*.25?'Votre budget restant est inférieur à 25 % du budget initial. Pensez à ralentir les dépenses non essentielles.':wallet&&wallet.balance>0?'Votre Cash Wallet est actif. Enregistrez chaque dépense cash pour garder une estimation fiable de ce qu’il vous reste.':'Commencez par préparer un Travel Pack et un budget : Kiwango pourra ensuite vous donner un résumé plus utile.'}</div></div>;
}

function Stat({ label, value, accent = false }) { return <div className={`rounded-2xl p-4 ${accent?'bg-emerald-50 text-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-100':'bg-white dark:bg-slate-950'}`}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-base font-semibold">{value}</p></div>; }
