import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Compass, CreditCard, ExternalLink, Lightbulb, Loader2, MapPin, Navigation, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { calculateCrossRate } from '../lib/rates';

const number = (v) => Number(String(v ?? '').replace(/\s/g, '').replace(',', '.'));
const fmt = (n, locale = 'fr-FR', digits = 2) => Number.isFinite(n) ? new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(n) : '—';
const read = (key, fallback) => { if (typeof window === 'undefined') return fallback; try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };

export default function KiwangoInsights({ allRates = {}, currencies = [], lang = 'fr' }) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const [section, setSection] = useState('trends');
  const buttons = [['trends','Tendance',BarChart3],['payments','Comparer',CreditCard],['nearby','Autour de moi',Compass],['coach','Mon résumé',Lightbulb]];
  return <section className="mt-8 min-w-0 overflow-hidden rounded-[30px] border border-slate-200/80 bg-slate-50/70 p-4 sm:p-6 dark:border-white/10 dark:bg-white/[.025]">
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700">Kiwango Insights</p><h2 className="mt-1 text-xl font-semibold tracking-[-.025em]">Comprendre, comparer et décider.</h2></div><div className="flex flex-wrap gap-2">{buttons.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`inline-flex items-center gap-2 rounded-full px-3.5 py-2 text-xs font-semibold transition ${section===id?'bg-emerald-600 text-white shadow-[0_8px_20px_rgba(5,150,105,.16)]':'bg-white text-slate-600 hover:bg-slate-100 dark:bg-white/5 dark:text-slate-300'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div>
    {section==='trends'&&<Trends currencies={currencies} locale={locale}/>} {section==='payments'&&<PaymentCompare allRates={allRates} currencies={currencies} locale={locale}/>} {section==='nearby'&&<Nearby locale={locale} lang={lang}/>} {section==='coach'&&<Coach allRates={allRates} locale={locale}/>} 
  </section>;
}

function CurrencySelect({ value, onChange, currencies }) { return <select value={value} onChange={onChange} className="min-w-0 rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-slate-950">{currencies.map(c=><option key={c.code} value={c.code}>{c.code} · {c.name}</option>)}</select>; }
const Stat = ({ label, value, accent = false }) => <div className={`rounded-2xl p-4 ${accent?'bg-emerald-50 text-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-100':'bg-white dark:bg-slate-950'}`}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-base font-semibold">{value}</p></div>;

function Trends({ currencies, locale }) {
  const [base,setBase]=useState('EUR'),[quote,setQuote]=useState('GMD'),[days,setDays]=useState(30),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/historical-rates?base=${base}&quote=${quote}&days=${days}`);const json=await r.json();if(!r.ok)throw new Error(json.error||'Unavailable');setData(json)}catch(e){setData(null);setError(e.message)}finally{setLoading(false)}},[base,quote,days]);
  useEffect(()=>{load()},[load]);
  const stats=useMemo(()=>{const values=data?.series?.map(p=>p.rate)||[];if(!values.length)return null;const current=values[values.length-1],first=values[0],avg=values.reduce((a,b)=>a+b,0)/values.length;return{current,first,avg,min:Math.min(...values),max:Math.max(...values),deltaAvg:(current/avg-1)*100,deltaPeriod:(current/first-1)*100}},[data]);
  const points=useMemo(()=>{if(!stats||!data?.series?.length)return'';const values=data.series.map(p=>p.rate);const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>`${(i/(values.length-1))*100},${92-((v-min)/range)*80}`).join(' ')},[data,stats]);
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="flex flex-wrap items-center gap-2"><CurrencySelect value={base} onChange={e=>setBase(e.target.value)} currencies={currencies}/><span className="text-slate-400">→</span><CurrencySelect value={quote} onChange={e=>setQuote(e.target.value)} currencies={currencies}/><div className="ml-auto flex gap-1 rounded-full bg-slate-100 p-1 dark:bg-white/5">{[7,30,90].map(value=><button key={value} onClick={()=>setDays(value)} className={`rounded-full px-3 py-1.5 text-[11px] font-semibold ${days===value?'bg-white text-slate-950 shadow-sm dark:bg-white dark:text-slate-950':'text-slate-500'}`}>{value} j</button>)}</div><button onClick={load} className="rounded-full p-2.5 text-slate-500 hover:bg-slate-100" aria-label="Actualiser"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>{loading&&<div className="mt-6 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Chargement de l’historique réel…</div>}{error&&<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Historique indisponible pour cette paire. Aucune donnée n’est simulée.</div>}{stats&&<><div className="mt-5 grid gap-4 lg:grid-cols-[1fr_260px]"><div className="rounded-[22px] bg-slate-50 p-4 dark:bg-white/[.03]"><svg viewBox="0 0 100 100" className="h-52 w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#059669" strokeWidth="2.2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="flex justify-between text-[10px] text-slate-400"><span>{data.series[0]?.date}</span><span>{data.series[data.series.length-1]?.date}</span></div></div><div className="grid gap-2"><Stat label="Actuel" value={`1 ${base} = ${fmt(stats.current,locale,4)} ${quote}`}/><Stat label={`Évolution ${days} j`} value={`${stats.deltaPeriod>=0?'+':''}${fmt(stats.deltaPeriod,locale,2)} %`} accent={stats.deltaPeriod>=0}/><Stat label="Vs moyenne" value={`${stats.deltaAvg>=0?'+':''}${fmt(stats.deltaAvg,locale,2)} %`}/></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Stat label="Moyenne" value={fmt(stats.avg,locale,4)}/><Stat label="Minimum" value={fmt(stats.min,locale,4)}/><Stat label="Maximum" value={fmt(stats.max,locale,4)}/></div></>}</div>;
}

function PaymentCompare({ allRates, currencies, locale }) {
  const [base,setBase]=useState('EUR'),[quote,setQuote]=useState('XOF'),[amount,setAmount]=useState('100');
  const [methods,setMethods]=useState([{id:1,name:'Cash / bureau',pct:1,fixed:0},{id:2,name:'Carte bancaire',pct:2.5,fixed:0},{id:3,name:'Transfert',pct:1.5,fixed:1}]);
  const rate=calculateCrossRate(base,quote,allRates,'EUR'),amt=number(amount); const results=methods.map((m)=>({...m,received:Number.isFinite(amt)&&rate?Math.max(0,amt-amt*m.pct/100-m.fixed)*rate:null,cost:Number.isFinite(amt)?amt*m.pct/100+m.fixed:null})).sort((a,b)=>(b.received||0)-(a.received||0));
  const update=(id,key,value)=>setMethods(methods.map(m=>m.id===id?{...m,[key]:key==='name'?value:number(value)||0}:m));
  const add=()=>setMethods([...methods,{id:Date.now(),name:'Nouvelle méthode',pct:0,fixed:0}]);
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><CurrencySelect value={base} onChange={e=>setBase(e.target.value)} currencies={currencies}/><CurrencySelect value={quote} onChange={e=>setQuote(e.target.value)} currencies={currencies}/><input value={amount} onChange={e=>setAmount(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-slate-950" placeholder="Montant"/><button onClick={add} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white dark:bg-white dark:text-slate-950"><Plus className="h-3.5 w-3.5"/>Méthode</button></div><p className="mt-3 text-xs text-slate-500">Les frais sont personnalisables. Kiwango ne présente aucun tarif opérateur comme “live” sans source officielle.</p><div className="mt-4 space-y-2">{results.map((m,index)=><div key={m.id} className={`grid min-w-0 gap-2 rounded-2xl border p-3 ${index===0?'border-emerald-300 bg-emerald-50/40 dark:border-emerald-800 dark:bg-emerald-950/10':'border-slate-200 bg-white dark:border-white/10 dark:bg-slate-950'} sm:grid-cols-[1fr_86px_86px_1fr_auto]`}><input value={m.name} onChange={e=>update(m.id,'name',e.target.value)} className="min-w-0 bg-transparent text-sm font-semibold outline-none"/><input value={m.pct} onChange={e=>update(m.id,'pct',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs dark:bg-white/5" aria-label="Frais pourcentage"/><input value={m.fixed} onChange={e=>update(m.id,'fixed',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs dark:bg-white/5" aria-label="Frais fixes"/><span className="self-center text-right"><strong className="block text-sm">{fmt(m.received,locale)} {quote}</strong><span className="text-[10px] text-slate-400">coût {fmt(m.cost,locale)} {base}</span></span><button onClick={()=>setMethods(methods.filter(x=>x.id!==m.id))} className="rounded-full p-2 text-slate-300 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div></div>;
}

function Nearby({ lang }) {
  const [status,setStatus]=useState('idle'),[items,setItems]=useState([]),[error,setError]=useState(null),[provider,setProvider]=useState(null),[radius,setRadius]=useState(2200);
  const find=()=>{if(!navigator.geolocation){setError('Géolocalisation indisponible');return}setStatus('loading');setError(null);navigator.geolocation.getCurrentPosition(async(pos)=>{try{const r=await fetch(`/api/nearby-finance?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&radius=${radius}&lang=${lang}`);const json=await r.json();if(!r.ok)throw new Error(json.error||'Erreur');setItems(json.items||[]);setProvider(json.provider);setStatus('ready')}catch(e){setError(e.message);setStatus('error')}},()=>{setError('Position refusée ou indisponible');setStatus('error')},{enableHighAccuracy:false,timeout:10000})};
  const labels={atm:'ATM',bank:'Banque',currency_exchange:'Bureau de change',bureau_de_change:'Bureau de change',money_transfer:'Transfert',financial_service:'Service financier'};
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-xl font-semibold">Services financiers autour de moi</h3><p className="mt-1 max-w-2xl text-sm text-slate-500">ATM, banques, bureaux de change et points de transfert. Google Places est utilisé quand la clé est configurée, avec OpenStreetMap en secours.</p></div><div className="flex items-end gap-2"><label className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Rayon<select value={radius} onChange={e=>setRadius(Number(e.target.value))} className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs normal-case tracking-normal text-slate-700 dark:border-white/10 dark:bg-slate-950 dark:text-slate-200"><option value={1000}>1 km</option><option value={2200}>2,2 km</option><option value={5000}>5 km</option></select></label><button onClick={find} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-slate-950"><Navigation className="h-4 w-4"/>{status==='loading'?'Recherche…':'Utiliser ma position'}</button></div></div>{provider&&<p className="mt-3 text-[11px] text-slate-400">Source cartographique : {provider}</p>}{error&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}<div className="mt-5 grid gap-2 md:grid-cols-2">{items.slice(0,20).map(item=>{const href=item.mapsUrl||`https://www.google.com/maps/search/?api=1&query=${item.lat},${item.lon}`;return <a key={item.id} href={href} target="_blank" rel="noreferrer" className="group flex min-w-0 items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 transition hover:border-emerald-300 hover:shadow-[0_12px_30px_rgba(15,23,42,.05)] dark:border-white/10 dark:bg-slate-950"><span className="flex h-10 w-10 flex-none items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><MapPin className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-2"><strong className="block truncate text-sm">{item.name||labels[item.type]||'Service financier'}</strong><ExternalLink className="h-3.5 w-3.5 flex-none text-slate-300 group-hover:text-emerald-600"/></span><span className="mt-1 block truncate text-xs text-slate-500">{labels[item.type]||item.type}{item.address?` · ${item.address}`:''}</span><span className="mt-2 flex flex-wrap gap-2 text-[10px] text-slate-400">{item.rating&&<span>★ {item.rating}{item.userRatingCount?` (${item.userRatingCount})`:''}</span>}{item.openNow===true&&<span className="text-emerald-600">Ouvert maintenant</span>}{item.openNow===false&&<span>Fermé actuellement</span>}</span></span></a>})}</div>{status==='ready'&&!items.length&&<p className="mt-5 text-sm text-slate-500">Aucun service référencé dans ce rayon.</p>}</div>;
}

function Coach({ allRates, locale }) {
  const budget=read('kiwango_budget',null),wallet=read('kiwango_wallet',null),fields=read('kiwango_field_rates',[]),alerts=read('kiwango_alerts',[]); const spent=budget?.expenses?.reduce((sum,e)=>sum+Number(e.amount||0),0)||0; const remaining=budget?Number(budget.total||0)-spent:null; const eurXof=calculateCrossRate('EUR','XOF',allRates,'EUR'); const budgetRatio=budget?.total>0?remaining/budget.total:null;
  const advice=[]; if(!budget)advice.push('Créez un budget voyage pour obtenir un suivi du reste à dépenser.'); else if(budgetRatio<.25)advice.push('Votre budget restant est inférieur à 25 % du budget initial : ralentissez les dépenses non essentielles.'); else advice.push('Votre budget reste dans une zone confortable par rapport au montant initial.'); if(wallet?.balance>0)advice.push('Votre Cash Wallet est actif : enregistrez les dépenses cash pour conserver une estimation fiable.'); else advice.push('Ajoutez votre cash local au Wallet si vous utilisez beaucoup d’espèces.'); if(fields.length)advice.push(`Vous avez ${fields.length} observation(s) terrain : comparez-les au Rate Check avant un nouveau change.`);
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><h3 className="text-xl font-semibold">Mon résumé Kiwango</h3><p className="mt-1 text-sm text-slate-500">Une synthèse contextuelle construite localement à partir de vos propres données.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Budget restant" value={budget?`${fmt(remaining,locale)} ${budget.currency}`:'À configurer'} accent={budgetRatio!=null&&budgetRatio>.25}/><Stat label="Cash disponible" value={wallet?`${fmt(wallet.balance,locale)} ${wallet.currency}`:'À configurer'}/><Stat label="Taux EUR/XOF" value={Number.isFinite(eurXof)?fmt(eurXof,locale,3):'Indisponible'}/><Stat label="Suivis" value={`${alerts.length} alertes · ${fields.length} terrain`}/></div><div className="mt-5 grid gap-2 md:grid-cols-3">{advice.slice(0,3).map((text,index)=><div key={index} className="rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-950 dark:bg-emerald-950/20 dark:text-emerald-100"><Lightbulb className="mb-2 h-4 w-4 text-emerald-600"/>{text}</div>)}</div></div>;
}
