import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Compass, CreditCard, ExternalLink, Lightbulb, Loader2, MapPin, Navigation, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { calculateCrossRate } from '../lib/rates';

const parseNumber = (value) => {
  const raw = String(value ?? '').trim().replace(/\s/g, '').replace(',', '.');
  if (!raw) return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
};
const nonNegative = (value) => { const n = parseNumber(value); return n !== null && n >= 0 ? n : null; };
const positive = (value) => { const n = parseNumber(value); return n !== null && n > 0 ? n : null; };
const fmt = (value, locale = 'fr-FR', digits = 2) => Number.isFinite(value) ? new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(value) : '—';
const read = (key, fallback) => { if (typeof window === 'undefined') return fallback; try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };

export default function KiwangoInsights({ allRates = {}, currencies = [], lang = 'fr' }) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const [section, setSection] = useState('trends');
  const tabs = [['trends','Tendance',BarChart3],['payments','Comparer',CreditCard],['nearby','Autour de moi',Compass],['coach','Mon résumé',Lightbulb]];
  return <section className="mt-8 min-w-0 overflow-hidden rounded-[30px] border border-slate-200/80 bg-slate-50/70 p-4 sm:p-6 dark:border-white/10 dark:bg-white/[.025]">
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700">Kiwango Insights</p><h2 className="mt-1 text-xl font-semibold tracking-[-.025em]">Comprendre, comparer et décider.</h2></div><div className="flex flex-wrap gap-2">{tabs.map(([id,label,Icon]) => <button key={id} onClick={() => setSection(id)} className={`inline-flex items-center gap-2 rounded-full px-3.5 py-2 text-xs font-semibold ${section === id ? 'bg-emerald-600 text-white' : 'bg-white text-slate-600 dark:bg-white/5 dark:text-slate-300'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div>
    {section === 'trends' && <Trends currencies={currencies} locale={locale}/>} {section === 'payments' && <PaymentCompare allRates={allRates} currencies={currencies} locale={locale}/>} {section === 'nearby' && <Nearby lang={lang}/>} {section === 'coach' && <Coach allRates={allRates} locale={locale}/>} 
  </section>;
}

function CurrencySelect({ value, onChange, currencies }) {
  return <select value={value} onChange={onChange} className="min-w-0 rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-slate-950">{currencies.map((currency) => <option key={currency.code} value={currency.code}>{currency.code} · {currency.name}</option>)}</select>;
}
function Stat({ label, value, accent = false }) {
  return <div className={`rounded-2xl p-4 ${accent ? 'bg-emerald-50 text-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-100' : 'bg-white dark:bg-slate-950'}`}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-base font-semibold">{value}</p></div>;
}

function Trends({ currencies, locale }) {
  const [base,setBase] = useState('EUR'); const [quote,setQuote] = useState('GMD'); const [days,setDays] = useState(30); const [data,setData] = useState(null); const [loading,setLoading] = useState(false); const [error,setError] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/historical-rates?base=${base}&quote=${quote}&days=${days}`); const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Unavailable'); const cleanSeries = Array.isArray(json.series) ? json.series.filter((point) => point?.date && Number.isFinite(Number(point.rate)) && Number(point.rate) > 0).map((point) => ({ ...point, rate: Number(point.rate) })) : []; if (!cleanSeries.length) throw new Error('NO_HISTORICAL_DATA'); setData({ ...json, series: cleanSeries }); } catch (e) { setData(null); setError(e.message); } finally { setLoading(false); } }, [base, quote, days]);
  useEffect(() => { load(); }, [load]);
  const stats = useMemo(() => { const values = data?.series?.map((point) => point.rate) || []; if (!values.length) return null; const current = values.at(-1); const first = values[0]; const avg = values.reduce((sum, value) => sum + value, 0) / values.length; return { current, avg, min: Math.min(...values), max: Math.max(...values), deltaAvg: avg > 0 ? (current / avg - 1) * 100 : null, deltaPeriod: values.length > 1 && first > 0 ? (current / first - 1) * 100 : null }; }, [data]);
  const points = useMemo(() => { const values = data?.series?.map((point) => point.rate) || []; if (values.length < 2) return ''; const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1; return values.map((value,index) => `${(index/(values.length-1))*100},${92-((value-min)/range)*80}`).join(' '); }, [data]);
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="flex flex-wrap items-center gap-2"><CurrencySelect value={base} onChange={(e) => setBase(e.target.value)} currencies={currencies}/><span className="text-slate-400">→</span><CurrencySelect value={quote} onChange={(e) => setQuote(e.target.value)} currencies={currencies}/><div className="ml-auto flex gap-1 rounded-full bg-slate-100 p-1 dark:bg-white/5">{[7,30,90].map((value) => <button key={value} onClick={() => setDays(value)} className={`rounded-full px-3 py-1.5 text-[11px] font-semibold ${days === value ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-500'}`}>{value} j</button>)}</div><button onClick={load} aria-label="Actualiser" className="rounded-full p-2.5 text-slate-500"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`}/></button></div>{loading && <div className="mt-6 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Chargement de l’historique réel…</div>}{error && <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Historique indisponible pour cette paire. Aucune donnée n’est simulée.</div>}{stats && <><div className="mt-5 grid gap-4 lg:grid-cols-[1fr_260px]"><div className="rounded-[22px] bg-slate-50 p-4 dark:bg-white/[.03]">{points ? <svg viewBox="0 0 100 100" className="h-52 w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#059669" strokeWidth="2.2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg> : <div className="flex h-52 items-center justify-center text-sm text-slate-400">Un seul point réel disponible : courbe non tracée.</div>}<div className="flex justify-between text-[10px] text-slate-400"><span>{data.series[0]?.date}</span><span>{data.series.at(-1)?.date}</span></div></div><div className="grid gap-2"><Stat label="Actuel" value={`1 ${base} = ${fmt(stats.current,locale,4)} ${quote}`}/><Stat label={`Évolution ${days} j`} value={stats.deltaPeriod === null ? 'Données insuffisantes' : `${stats.deltaPeriod >= 0 ? '+' : ''}${fmt(stats.deltaPeriod,locale,2)} %`} accent={stats.deltaPeriod !== null && stats.deltaPeriod >= 0}/><Stat label="Vs moyenne" value={stats.deltaAvg === null ? '—' : `${stats.deltaAvg >= 0 ? '+' : ''}${fmt(stats.deltaAvg,locale,2)} %`}/></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Stat label="Moyenne" value={fmt(stats.avg,locale,4)}/><Stat label="Minimum" value={fmt(stats.min,locale,4)}/><Stat label="Maximum" value={fmt(stats.max,locale,4)}/></div></>}</div>;
}

function PaymentCompare({ allRates, currencies, locale }) {
  const [base,setBase] = useState('EUR'); const [quote,setQuote] = useState('XOF'); const [amount,setAmount] = useState('100');
  const [methods,setMethods] = useState([{id:1,name:'Cash / bureau',pct:'1',fixed:'0'},{id:2,name:'Carte bancaire',pct:'2.5',fixed:'0'},{id:3,name:'Transfert',pct:'1.5',fixed:'1'}]);
  const rate = calculateCrossRate(base,quote,allRates,'EUR'); const amt = positive(amount);
  const results = methods.map((method) => { const pct = nonNegative(method.pct); const fixed = nonNegative(method.fixed); const valid = amt !== null && pct !== null && fixed !== null && Number.isFinite(rate) && rate > 0; const cost = valid ? amt*pct/100+fixed : null; return { ...method, valid, cost, received: valid ? Math.max(0,amt-cost)*rate : null }; }).sort((a,b) => (b.received ?? -1) - (a.received ?? -1));
  const update = (id,key,value) => setMethods((current) => current.map((method) => method.id === id ? { ...method, [key]: value } : method));
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><CurrencySelect value={base} onChange={(e) => setBase(e.target.value)} currencies={currencies}/><CurrencySelect value={quote} onChange={(e) => setQuote(e.target.value)} currencies={currencies}/><input value={amount} onChange={(e) => setAmount(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-slate-950" placeholder="Montant"/><button onClick={() => setMethods((current) => [...current,{id:Date.now(),name:'Nouvelle méthode',pct:'0',fixed:'0'}])} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white dark:bg-white dark:text-slate-950"><Plus className="h-3.5 w-3.5"/>Méthode</button></div><p className="mt-3 text-xs text-slate-500">Les frais doivent être positifs ou nuls. Aucun tarif opérateur n’est présenté comme live sans source officielle.</p><div className="mt-4 space-y-2">{results.map((method,index) => <div key={method.id} className={`grid gap-2 rounded-2xl border p-3 ${index === 0 && method.valid ? 'border-emerald-300 bg-emerald-50/40' : 'border-slate-200'} sm:grid-cols-[1fr_86px_86px_1fr_auto]`}><input value={method.name} onChange={(e) => update(method.id,'name',e.target.value)} className="min-w-0 bg-transparent text-sm font-semibold outline-none"/><input value={method.pct} onChange={(e) => update(method.id,'pct',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs" aria-label="Frais pourcentage"/><input value={method.fixed} onChange={(e) => update(method.id,'fixed',e.target.value)} className="min-w-0 rounded-xl bg-slate-50 px-2 py-2 text-xs" aria-label="Frais fixes"/><span className="self-center text-right"><strong className="block text-sm">{method.valid ? `${fmt(method.received,locale)} ${quote}` : 'Valeurs invalides'}</strong><span className="text-[10px] text-slate-400">coût {fmt(method.cost,locale)} {base}</span></span><button onClick={() => setMethods((current) => current.filter((item) => item.id !== method.id))} className="rounded-full p-2 text-slate-300 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div></div>;
}

function Nearby({ lang }) {
  const [status,setStatus] = useState('idle'); const [items,setItems] = useState([]); const [error,setError] = useState(null); const [provider,setProvider] = useState(null); const [radius,setRadius] = useState(2200);
  const find = () => { if (typeof navigator === 'undefined' || !navigator.geolocation) { setError('Géolocalisation indisponible'); return; } setStatus('loading'); setError(null); navigator.geolocation.getCurrentPosition(async (position) => { try { const response = await fetch(`/api/nearby-finance?lat=${position.coords.latitude}&lon=${position.coords.longitude}&radius=${radius}&lang=${lang}`); const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Erreur'); setItems(Array.isArray(json.items) ? json.items : []); setProvider(json.provider || null); setStatus('ready'); } catch (e) { setItems([]); setError(e.message); setStatus('error'); } }, () => { setItems([]); setError('Position refusée ou indisponible'); setStatus('error'); }, { enableHighAccuracy:false, timeout:10000 }); };
  const labels = { atm:'ATM', bank:'Banque', currency_exchange:'Bureau de change', bureau_de_change:'Bureau de change', money_transfer:'Transfert', financial_service:'Service financier' };
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-xl font-semibold">Services financiers autour de moi</h3><p className="mt-1 max-w-2xl text-sm text-slate-500">Google Places est utilisé quand configuré, OpenStreetMap sert de secours.</p></div><div className="flex items-end gap-2"><label className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Rayon<select value={radius} onChange={(e) => setRadius(Number(e.target.value))} className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs"><option value={1000}>1 km</option><option value={2200}>2,2 km</option><option value={5000}>5 km</option></select></label><button disabled={status === 'loading'} onClick={find} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60"><Navigation className="h-4 w-4"/>{status === 'loading' ? 'Recherche…' : 'Utiliser ma position'}</button></div></div>{provider && <p className="mt-3 text-[11px] text-slate-400">Source cartographique : {provider}</p>}{error && <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}<div className="mt-5 grid gap-2 md:grid-cols-2">{items.slice(0,20).map((item) => { const href = item.mapsUrl || `https://www.google.com/maps/search/?api=1&query=${item.lat},${item.lon}`; return <a key={item.id} href={href} target="_blank" rel="noreferrer" className="group flex min-w-0 items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4"><span className="flex h-10 w-10 flex-none items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><MapPin className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-2"><strong className="block truncate text-sm">{item.name || labels[item.type] || 'Service financier'}</strong><ExternalLink className="h-3.5 w-3.5 flex-none text-slate-300"/></span><span className="mt-1 block truncate text-xs text-slate-500">{labels[item.type] || item.type}{item.address ? ` · ${item.address}` : ''}</span></span></a>; })}</div>{status === 'ready' && !items.length && <p className="mt-5 text-sm text-slate-500">Aucun service référencé dans ce rayon.</p>}</div>;
}

function Coach({ allRates, locale }) {
  const budget = read('kiwango_budget', null); const wallet = read('kiwango_wallet', null); const fields = read('kiwango_field_rates', []); const alerts = read('kiwango_alerts', []);
  const expenses = Array.isArray(budget?.expenses) ? budget.expenses : [];
  const spent = expenses.reduce((sum,item) => sum + (nonNegative(item.amount) ?? 0), 0);
  const total = nonNegative(budget?.total); const remaining = total === null ? null : total - spent; const ratio = total && total > 0 ? remaining / total : null;
  const eurXof = calculateCrossRate('EUR','XOF',allRates,'EUR');
  const advice = [];
  if (!budget || total === null) advice.push('Créez un budget voyage pour obtenir un suivi fiable du reste à dépenser.'); else if (ratio < 0) advice.push('Votre budget est dépassé : vérifiez les dernières dépenses enregistrées.'); else if (ratio < .25) advice.push('Votre budget restant est inférieur à 25 % du montant initial.'); else advice.push('Votre budget reste dans une zone confortable par rapport au montant initial.');
  const walletBalance = nonNegative(wallet?.balance); if (walletBalance !== null && walletBalance > 0) advice.push('Votre Cash Wallet est actif : continuez à enregistrer vos dépenses cash.'); else advice.push('Ajoutez votre cash local au Wallet si vous utilisez des espèces.');
  if (Array.isArray(fields) && fields.length) advice.push(`Vous avez ${fields.length} observation(s) terrain : comparez-les au Rate Check avant un nouveau change.`);
  return <div className="rounded-[24px] border border-slate-200 bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-slate-950/70"><h3 className="text-xl font-semibold">Mon résumé Kiwango</h3><p className="mt-1 text-sm text-slate-500">Synthèse locale basée uniquement sur vos données enregistrées.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Budget restant" value={remaining === null ? 'À configurer' : `${fmt(remaining,locale)} ${budget.currency || ''}`} accent={ratio !== null && ratio > .25}/><Stat label="Cash disponible" value={walletBalance === null ? 'À configurer' : `${fmt(walletBalance,locale)} ${wallet.currency || ''}`}/><Stat label="Taux EUR/XOF" value={Number.isFinite(eurXof) ? fmt(eurXof,locale,3) : 'Indisponible'}/><Stat label="Suivis" value={`${Array.isArray(alerts) ? alerts.length : 0} alertes · ${Array.isArray(fields) ? fields.length : 0} terrain`}/></div><div className="mt-5 grid gap-2 md:grid-cols-3">{advice.slice(0,3).map((text,index) => <div key={index} className="rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-950"><Lightbulb className="mb-2 h-4 w-4 text-emerald-600"/>{text}</div>)}</div></div>;
}
