import React from 'react';
import { WifiOff, Zap, ShieldCheck, Coins, ArrowUpRight } from 'lucide-react';
import { getTranslation } from '../lib/i18n';

export default function LandingFeatures({ lang = 'fr' }) {
  const features = [
    { icon: WifiOff, titleKey: 'featureOfflineTitle', descKey: 'featureOfflineDesc', accent: 'from-emerald-50 to-white dark:from-emerald-950/30 dark:to-slate-950' },
    { icon: Coins, titleKey: 'featureCurrenciesTitle', descKey: 'featureCurrenciesDesc', accent: 'from-lime-50 to-white dark:from-lime-950/20 dark:to-slate-950' },
    { icon: Zap, titleKey: 'featureSpeedTitle', descKey: 'featureSpeedDesc', accent: 'from-teal-50 to-white dark:from-teal-950/20 dark:to-slate-950' },
    { icon: ShieldCheck, titleKey: 'featureCacheTitle', descKey: 'featureCacheDesc', accent: 'from-slate-50 to-white dark:from-slate-900 dark:to-slate-950' },
  ];

  return <section className="py-14 md:py-20"><div className="mb-9 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-400">Kiwango</p><h2 className="text-3xl font-semibold tracking-[-.04em] text-slate-950 dark:text-white md:text-4xl">{getTranslation(lang,'whyChoose')}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500 dark:text-slate-400">{getTranslation(lang,'whyChooseSubtitle')}</p></div><p className="max-w-xs text-sm leading-6 text-slate-400">{lang==='fr'?'Une expérience pensée pour rester rapide, claire et utile quand le réseau devient incertain.':'An experience designed to stay fast, clear and useful when connectivity becomes uncertain.'}</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{features.map((feature)=>{const Icon=feature.icon;return <article key={feature.titleKey} className={`group relative overflow-hidden rounded-[28px] border border-slate-200/80 bg-gradient-to-br ${feature.accent} p-6 shadow-[0_18px_55px_-40px_rgba(15,23,42,.45)] transition-all duration-300 hover:-translate-y-1 hover:border-emerald-300 dark:border-white/10`}><div className="mb-10 flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-emerald-200 bg-white/80 text-emerald-700 shadow-sm dark:border-emerald-900 dark:bg-slate-900/80 dark:text-emerald-400"><Icon className="h-5 w-5" strokeWidth={1.8}/></div><ArrowUpRight className="h-4 w-4 text-slate-300 transition group-hover:text-emerald-600"/></div><h3 className="text-base font-semibold tracking-[-.02em] text-slate-950 dark:text-white">{getTranslation(lang,feature.titleKey)}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{getTranslation(lang,feature.descKey)}</p></article>})}</div></section>;
}
