import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, Check, ChevronRight, DownloadCloud, Globe2, Loader2, MapPin, Plane, RefreshCw, Search, ShieldCheck, WifiOff } from 'lucide-react';
import * as Flags from 'country-flag-icons/react/3x2';
import { getPreparedTrip, getPreparedTrips, savePreparedTrip } from '../lib/db';
import { getExchangeRates, calculateCrossRate } from '../lib/rates';
import { TRAVEL_DESTINATIONS } from '../lib/travel';
import TripPreparation from './TripPreparation';
import { getCountryDirectory } from '../lib/country-directory-client';

const Flag = ({ code, className = 'h-6 w-9' }) => { const Component = Flags[code?.toUpperCase()]; return Component ? <Component className={`${className} rounded-md border border-black/5 object-cover shadow-sm`} /> : <Globe2 className="h-5 w-5 text-slate-400"/>; };
const localizedCountryName = (country, lang) => { try { return new Intl.DisplayNames([lang === 'en' ? 'en' : 'fr'], { type: 'region' }).of(country.code) || country.name; } catch { return country.name; } };
const fallbackCountries = () => TRAVEL_DESTINATIONS.map((item) => ({ code:item.code, code3:item.code, name:item.country, officialName:item.country, region:'Africa', subregion:null, capital:null, flag:item.flag, currencies:[{code:item.currency,name:item.currency,symbol:item.currency}], primaryCurrency:{code:item.currency,name:item.currency,symbol:item.currency} }));
const buildPairs = (currencyCode) => { const preferred=['XOF','EUR','USD','GBP']; if(currencyCode==='XOF')preferred.unshift('GMD'); if(currencyCode==='XAF')preferred.unshift('XOF'); return [...new Set(preferred)].filter((code)=>code!==currencyCode).slice(0,4); };
const packAge = (trip) => { const timestamp=Number(trip?.rateTimestamp||trip?.preparedAt); if(!timestamp)return {level:'unknown',hours:null}; const hours=Math.max(0,(Date.now()-timestamp)/3600000); return {hours,level:hours<6?'fresh':hours<24?'aging':hours<72?'stale':'old'}; };

export default function TravelMode({ lang='fr', onSelectPair }) {
  const fr = lang === 'fr';
  const [countries,setCountries]=useState([]); const [destinationCode,setDestinationCode]=useState('SN'); const [selectedCurrencyCode,setSelectedCurrencyCode]=useState(null); const [query,setQuery]=useState(''); const [region,setRegion]=useState('all'); const [directoryStatus,setDirectoryStatus]=useState('loading'); const [preparedTrip,setPreparedTrip]=useState(null); const [preparedTrips,setPreparedTrips]=useState([]); const [status,setStatus]=useState('idle'); const [rates,setRates]=useState({}); const [activeTrip,setActiveTrip]=useState(null);

  useEffect(()=>{ const params=new URLSearchParams(window.location.search); const fromUrl=params.get('country')?.toUpperCase(); const saved=localStorage.getItem('kiwango_quick_destination'); if(fromUrl)setDestinationCode(fromUrl); else if(saved)setDestinationCode(saved); try { const trip=JSON.parse(localStorage.getItem('kiwango_active_trip')); if(trip?.destinationCode){setActiveTrip(trip);setDestinationCode(trip.destinationCode);} } catch {} },[]);
  useEffect(()=>{ let cancelled=false; const fallback=fallbackCountries(); getCountryDirectory(fallback).then(({countries:directory,source})=>{if(cancelled)return;setCountries(directory);setDirectoryStatus(source==='fallback'?'fallback':'ready');}); getPreparedTrips().then((items)=>!cancelled&&setPreparedTrips(items)); return()=>{cancelled=true}; },[]);

  const destination=useMemo(()=>countries.find((c)=>c.code===destinationCode)||countries[0]||null,[countries,destinationCode]);
  const localName=destination?localizedCountryName(destination,lang):''; const availableCurrencies=destination?.currencies||[]; const primaryCurrency=availableCurrencies.find((currency)=>currency.code===selectedCurrencyCode)||destination?.primaryCurrency||availableCurrencies[0]||null; const pairTargets=useMemo(()=>primaryCurrency?buildPairs(primaryCurrency.code):[],[primaryCurrency]);
  useEffect(()=>{ if(!destination?.code)return; localStorage.setItem('kiwango_quick_destination',destination.code); setSelectedCurrencyCode(null); let cancelled=false; getPreparedTrip(destination.code).then((trip)=>{if(cancelled)return;setPreparedTrip(trip);if(trip?.currency)setSelectedCurrencyCode(trip.currency);}); return()=>{cancelled=true}; },[destination?.code]);

  const regions=useMemo(()=>['all',...new Set(countries.map(c=>c.region).filter(Boolean))],[countries]);
  const filteredCountries=useMemo(()=>{const needle=query.trim().toLowerCase();return countries.filter((country)=>{if(region!=='all'&&country.region!==region)return false;if(!needle)return true;const name=localizedCountryName(country,lang).toLowerCase();const currencies=(country.currencies||[]).map(i=>`${i.code} ${i.name}`).join(' ').toLowerCase();return name.includes(needle)||country.name?.toLowerCase().includes(needle)||country.code?.toLowerCase().includes(needle)||currencies.includes(needle);});},[countries,query,region,lang]);

  const prepareOffline=async()=>{if(!destination||!primaryCurrency)return;setStatus('syncing');try{const data=await getExchangeRates('EUR',true);const usablePairs=pairTargets.map(counter=>({from:primaryCurrency.code,to:counter,rate:calculateCrossRate(primaryCurrency.code,counter,data?.rates||{},'EUR')})).filter(pair=>Number.isFinite(pair.rate));if(!data?.rates||!usablePairs.length){setStatus('error');return;}const trip={countryCode:destination.code,country:localName,currency:primaryCurrency.code,currencyName:primaryCurrency.name,currencies:availableCurrencies,capital:destination.capital,region:destination.region,pairs:usablePairs,rateSource:data.source,rateTimestamp:data.timestamp};const persisted=await savePreparedTrip(trip);if(!persisted)throw new Error('trip-persistence');setRates(data.rates);const refreshed=await getPreparedTrip(destination.code);if(!refreshed)throw new Error('trip-verification');setPreparedTrip(refreshed);setPreparedTrips(await getPreparedTrips());setStatus('ready');}catch{setStatus('error')}};

  const samePreparedCurrency=preparedTrip?.countryCode===destination?.code&&preparedTrip?.currency===primaryCurrency?.code; const pairs=samePreparedCurrency&&preparedTrip?.pairs?.length?preparedTrip.pairs:pairTargets.map(counter=>({from:primaryCurrency?.code,to:counter,rate:primaryCurrency?calculateCrossRate(primaryCurrency.code,counter,rates,'EUR'):null}));
  const referencePair=pairs.find(p=>p.to==='XOF')||pairs.find(p=>p.to==='EUR')||pairs.find(p=>Number.isFinite(p.rate)); const quickAmounts=[10,50,100,500,1000]; const preparedAt=samePreparedCurrency?(preparedTrip?.rateTimestamp||preparedTrip?.preparedAt):null; const freshness=samePreparedCurrency?packAge(preparedTrip):{level:'unknown',hours:null}; const formatDate=(ts)=>!ts?'—':new Intl.DateTimeFormat(fr?'fr-FR':'en-US',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(ts)); const freshnessText=freshness.level==='fresh'?(fr?'Données récentes':'Fresh data'):freshness.level==='aging'?(fr?'À actualiser bientôt':'Refresh soon'):freshness.level==='stale'?(fr?'Données anciennes':'Stale data'):freshness.level==='old'?(fr?'Données très anciennes':'Very old data'):null;

  if(!destination&&directoryStatus==='loading')return <div className="flex min-h-[420px] items-center justify-center gap-3 text-sm text-slate-500"><Loader2 className="h-5 w-5 animate-spin text-emerald-600"/>{fr?'Chargement des destinations…':'Loading destinations…'}</div>;
  if(!destination)return <div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{fr?'Le répertoire des destinations est indisponible.':'Destination directory is unavailable.'}</div>;

  return <section className="min-w-0 space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-emerald-700">{fr?'Voyage':'Travel'}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{fr?'Préparer une destination':'Prepare a destination'}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{fr?'Choisissez le pays, vérifiez sa devise et préparez les données dont vous aurez réellement besoin sur place.':'Choose the country, confirm its currency and prepare the data you will actually need on arrival.'}</p></div><span className="text-xs text-slate-400">{directoryStatus==='ready'?`${countries.length} destinations`:(fr?'Répertoire de secours':'Fallback directory')}</span></div>

    {activeTrip&&<div className="grid gap-4 border border-emerald-200 bg-emerald-50/70 p-5 sm:grid-cols-[1fr_auto] sm:items-center dark:border-emerald-900/60 dark:bg-emerald-950/20"><div className="flex items-start gap-3"><span className="flex h-10 w-10 flex-none items-center justify-center bg-emerald-600 text-white"><Plane className="h-5 w-5"/></span><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700 dark:text-emerald-300">{fr?'Votre voyage actif':'Your active trip'}</p><h2 className="mt-1 text-lg font-semibold">{activeTrip.originName} <span className="mx-1 text-emerald-600">→</span> {activeTrip.destinationName}</h2><p className="mt-1 text-xs text-slate-500">{activeTrip.originCurrency} → {activeTrip.destinationCurrency}</p></div></div>{activeTrip.departureDate&&<span className="inline-flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-slate-300"><CalendarDays className="h-4 w-4 text-emerald-600"/>{new Intl.DateTimeFormat(fr?'fr-FR':'en-US',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${activeTrip.departureDate}T12:00:00`))}</span>}</div>}

    {preparedTrips.length>0&&<div className="rounded-[26px] border border-slate-200/80 bg-white p-5 dark:border-white/10 dark:bg-white/[.03]"><div className="mb-4 flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">{fr?'Mes voyages préparés':'Prepared trips'}</p><h2 className="mt-1 text-lg font-semibold">{fr?'Reprendre rapidement':'Resume quickly'}</h2></div><ShieldCheck className="h-5 w-5 text-emerald-600"/></div><div className="flex flex-wrap gap-2">{preparedTrips.slice(0,6).map((trip)=>{const age=packAge(trip);return <button key={trip.countryCode} onClick={()=>setDestinationCode(trip.countryCode)} className={`rounded-2xl border px-3.5 py-3 text-left transition ${destinationCode===trip.countryCode?'border-emerald-300 bg-emerald-50 dark:border-emerald-700/50 dark:bg-emerald-950/30':'border-slate-200 hover:border-emerald-300 dark:border-white/10'}`}><span className="block text-sm font-semibold">{trip.country}</span><span className="mt-1 block text-xs text-slate-400">{trip.currency} · {formatDate(trip.preparedAt||trip.rateTimestamp)}</span>{['stale','old'].includes(age.level)&&<span className="mt-1 block text-[10px] font-semibold text-amber-600">{fr?'À resynchroniser':'Resync recommended'}</span>}</button>})}</div></div>}

    <div className="grid min-w-0 gap-6 lg:grid-cols-[.85fr_1.15fr]">
      <aside className="min-w-0 rounded-[28px] border border-slate-200/80 bg-white p-4 shadow-[0_18px_50px_rgba(15,23,42,.04)] dark:border-white/10 dark:bg-white/[.03]"><div className="px-1"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">{fr?'Destination':'Destination'}</p><h2 className="mt-1 text-lg font-semibold">{fr?'Où allez-vous ?':'Where are you going?'}</h2></div><label className="mt-4 flex min-w-0 items-center gap-2 rounded-2xl border border-slate-200 px-3.5 py-3 focus-within:border-emerald-400 focus-within:ring-4 focus-within:ring-emerald-500/10 dark:border-white/10"><Search className="h-4 w-4 flex-none text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={fr?'Pays, code ou devise…':'Country, code or currency…'} className="w-full min-w-0 bg-transparent text-sm outline-none"/></label><div className="mt-3 flex flex-wrap gap-2">{regions.map(item=><button key={item} onClick={()=>setRegion(item)} className={`rounded-full px-3 py-1.5 text-[11px] font-semibold ${region===item?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'bg-slate-100 text-slate-500 dark:bg-white/5 dark:text-slate-300'}`}>{item==='all'?(fr?'Tous':'All'):item}</button>)}</div><div className="mt-4 max-h-[570px] space-y-1 overflow-y-auto pr-1">{filteredCountries.map(item=>{const active=destinationCode===item.code;const currencies=item.currencies||[];const currency=item.primaryCurrency||currencies[0];return <button key={item.code} onClick={()=>{setDestinationCode(item.code);setStatus('idle');setPreparedTrip(null)}} className={`flex w-full items-center justify-between rounded-2xl border px-3.5 py-3 text-left transition ${active?'border-emerald-300 bg-emerald-50/80 dark:border-emerald-700/50 dark:bg-emerald-950/30':'border-transparent hover:border-slate-200 hover:bg-slate-50 dark:hover:border-white/10 dark:hover:bg-white/[.025]'}`}><span className="flex min-w-0 items-center gap-3"><Flag code={item.flag}/><span className="min-w-0"><span className="block truncate text-sm font-semibold">{localizedCountryName(item,lang)}</span><span className="block truncate text-xs text-slate-500">{currencies.length>1?currencies.map(c=>c.code).join(' / '):`${currency?.code||'—'} · ${currency?.name||'—'}`}</span></span></span>{active?<span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-600 text-white"><Check className="h-3.5 w-3.5"/></span>:<ChevronRight className="h-4 w-4 text-slate-300"/>}</button>})}</div></aside>

      <div className="min-w-0 space-y-5">
        <div className="overflow-hidden rounded-[28px] border border-slate-200/80 bg-white shadow-[0_18px_54px_rgba(15,23,42,.05)] dark:border-white/10 dark:bg-white/[.03]"><div className="border-b border-slate-200/80 p-5 sm:p-6 dark:border-white/10"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-sm text-slate-500"><MapPin className="h-4 w-4 text-emerald-600"/>{localName}{destination.capital?` · ${destination.capital}`:''}</div><div className="flex items-center gap-3"><Flag code={destination.flag} className="h-9 w-14"/><div><p className="text-2xl font-semibold">{primaryCurrency?.code||'—'}</p><p className="text-xs text-slate-500">{primaryCurrency?.name||'—'}</p></div></div></div>{samePreparedCurrency?<span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${['stale','old'].includes(freshness.level)?'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300':'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300'}`}>{['stale','old'].includes(freshness.level)?<AlertTriangle className="h-3.5 w-3.5"/>:<ShieldCheck className="h-3.5 w-3.5"/>}{freshnessText|| (fr?'Prêt hors ligne':'Offline ready')}</span>:<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-500 dark:bg-white/5">{fr?'À préparer':'Not prepared'}</span>}</div></div>
          <div className="p-5 sm:p-6">{availableCurrencies.length>1&&<div className="mb-5 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-white/10 dark:bg-white/[.025]"><p className="text-xs font-semibold">{fr?'Plusieurs devises disponibles':'Multiple currencies available'}</p><p className="mt-1 text-xs text-slate-500">{fr?'Choisissez la devise à préparer pour ce voyage.':'Choose the currency to prepare for this trip.'}</p><div className="mt-3 flex flex-wrap gap-2">{availableCurrencies.map(currency=><button key={currency.code} onClick={()=>{setSelectedCurrencyCode(currency.code);setStatus('idle')}} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${primaryCurrency?.code===currency.code?'border-emerald-400 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200':'border-slate-200 bg-white text-slate-600 dark:border-white/10 dark:bg-white/[.03] dark:text-slate-300'}`}>{currency.code}{currency.name?` · ${currency.name}`:''}</button>)}</div></div>}{samePreparedCurrency&&['stale','old'].includes(freshness.level)&&<div className="mb-5 flex items-start gap-2 rounded-2xl border border-amber-200 bg-amber-50 px-3.5 py-3 text-xs text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle className="mt-0.5 h-4 w-4 flex-none"/><span>{freshness.level==='old'?(fr?'Ce Travel Pack date de plus de 3 jours. Il reste disponible hors connexion, mais resynchronisez-le dès que possible avant de vous fier aux taux.':'This Travel Pack is more than 3 days old. It remains available offline, but resync it as soon as possible before relying on the rates.'):(fr?'Les taux de ce Travel Pack ont plus de 24 heures. Vous pouvez les consulter hors connexion, mais une resynchronisation est recommandée.':'Rates in this Travel Pack are more than 24 hours old. You can still use them offline, but resync is recommended.')}</span></div>}<div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.025]"><p className="text-[11px] text-slate-400">{fr?'Devise locale':'Local currency'}</p><p className="mt-1 text-lg font-semibold">{primaryCurrency?.code||'—'}</p></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.025]"><p className="text-[11px] text-slate-400">{fr?'Dernière synchro':'Last sync'}</p><p className="mt-1 text-sm font-semibold">{formatDate(preparedAt)}</p></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[.025]"><p className="text-[11px] text-slate-400">{fr?'Paires utiles':'Useful pairs'}</p><p className="mt-1 text-lg font-semibold">{pairs.length}</p></div></div>
            <div className="mt-5"><div className="mb-3 flex items-center justify-between"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">{fr?'Paires utiles':'Useful pairs'}</p><span className="text-[11px] text-slate-400">{primaryCurrency?.code}</span></div><div className="grid gap-2 sm:grid-cols-2">{pairs.map(pair=><button key={`${pair.from}-${pair.to}`} onClick={()=>onSelectPair?.(pair.from,pair.to)} className="rounded-2xl border border-slate-200/80 bg-slate-50/70 p-3.5 text-left transition hover:border-emerald-300 hover:bg-white dark:border-white/10 dark:bg-white/[.025]"><span className="block text-sm font-semibold">{pair.from} ↔ {pair.to}</span><span className="mt-1 block text-xs text-slate-500">{Number.isFinite(pair.rate)?`1 ${pair.from} = ${pair.rate.toLocaleString(fr?'fr-FR':'en-US',{maximumFractionDigits:4})} ${pair.to}`:(fr?'À synchroniser':'Sync required')}</span></button>)}</div></div>
            {referencePair&&Number.isFinite(referencePair.rate)&&<div className="mt-6"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">Cheat sheet</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{quickAmounts.map(value=><button key={value} onClick={()=>onSelectPair?.(referencePair.from,referencePair.to)} className="rounded-2xl border border-slate-200 px-3 py-3 text-left hover:border-emerald-300 dark:border-white/10"><span className="block text-xs font-semibold">{value.toLocaleString()} {referencePair.from}</span><span className="mt-1 block text-[11px] text-slate-500">≈ {(value*referencePair.rate).toLocaleString(fr?'fr-FR':'en-US',{maximumFractionDigits:0})} {referencePair.to}</span></button>)}</div></div>}
            {status==='error'&&<div className="mt-4 flex items-start gap-2 rounded-2xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200"><WifiOff className="mt-0.5 h-3.5 w-3.5"/>{fr?'Impossible de préparer ce Travel Pack de façon fiable. Vérifiez votre connexion et réessayez.':'Unable to prepare this Travel Pack reliably. Check your connection and try again.'}</div>}
            <button onClick={prepareOffline} disabled={status==='syncing'||!primaryCurrency} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-4 py-3.5 text-sm font-semibold text-white shadow-[0_12px_28px_rgba(5,150,105,.18)] hover:bg-emerald-700 disabled:opacity-60">{status==='syncing'?<><RefreshCw className="h-4 w-4 animate-spin"/>{fr?'Synchronisation…':'Syncing…'}</>:<><DownloadCloud className="h-4 w-4"/>{samePreparedCurrency?(fr?'Mettre à jour le Travel Pack':'Update Travel Pack'):(fr?`Préparer ${localName} hors connexion`:`Prepare ${localName} offline`)}</>}</button>
          </div></div>
      </div>
    </div>

    <div><div className="mb-4 max-w-3xl"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700">{fr?'Plan de voyage personnalisé':'Personal trip plan'}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em]">{fr?`Préparez concrètement votre séjour : ${localName}`:`Prepare your stay: ${localName}`}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{fr?'Centralisez votre point de départ, vos dates, votre checklist et des raccourcis Google Maps réellement utiles. Toutes les données du plan restent sur votre appareil.':'Keep your departure point, dates, checklist and genuinely useful Google Maps shortcuts together. All plan data stays on your device.'}</p></div><TripPreparation country={{...destination,name:localName}} lang={lang} activeTrip={activeTrip}/></div>
  </section>;
}
